mcs/urls.py
from django.contrib import admin
from django.urls import path, include

from core import views as coreviews
from servers import views as serverview
from dashboard import views as dashboardviews

urlpatterns = [
    path('', dashboardviews.index, name="index"),

    path('admin/', admin.site.urls),

    path('test/', coreviews.index, name='test'),
    path('hello/', coreviews.say_hello, name="hello"),
    path('ban/', coreviews.ban_player, name="ban"),

    path('servers/', serverview.index, name='server-overview'),
    path('server/edit/<str:server_identifier>', serverview.edit_server, name='server-edit'),
    path('server/remove-world/<str:server_identifier>', serverview.remove_world, name='server-remove-world'),
    path('server/upload-world/<str:server_identifier>', serverview.upload_world, name='server-upload-world'),
    path('server/delete/<str:server_identifier>', serverview.delete_server, name='server-delete'),
    path('server/console/<str:server_identifier>', serverview.show_server_console, name='server-console'),
    path('new-server/', serverview.new_server, name='new-server'),
    path('server/binaries/', serverview.binaries_overview, name="server-binaries-overview"),
    path('server/binaries/download', serverview.download_binary, name="server-binaries-download"),
    path('server/start/<str:server_identifier>', serverview.start_server, name="server-start-server"),
    path('server/stop/<str:server_identifier>', serverview.stop_server, name="server-stop-server"),
    path('server/restart/<str:server_identifier>', serverview.restart_server, name="server-restart-server"),

    path('start-server/', dashboardviews.start_server, name="dashboard-start-server"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/profile/', coreviews.profile_page, name="profile"),

    path('prometheus/', include('django_prometheus.urls')),
]

servers/models.py
from datetime import datetime
import random

import requests
import uuid as uuid
from django.core.validators import MinValueValidator, MaxValueValidator
from django.conf import settings
from django.db import models
from core.choices import DIFFICULTY, GAMEMODES, SERVER_TYPE
import os


class ServerBin(models.Model):
    class Meta:
        verbose_name = 'Server Binary'
        verbose_name_plural = 'Server Binaries'

    name = models.CharField(max_length=500, blank=False, null=False)
    type = models.IntegerField(choices=SERVER_TYPE, default=0)
    version = models.CharField(max_length=10, blank=False, null=False)
    download_path = models.URLField(blank=False, null=False)

    binary_name = models.CharField(max_length=200, blank=True, help_text="this gets set when saving")

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):

        url = self.download_path
        self.binary_name = url.rsplit('/', 1)[-1]
        super().save()

        if not os.path.exists(os.path.join(settings.BINARY_DIR, self.binary_name)):
            server_jar = requests.get(url)
            open(os.path.join(settings.BINARY_DIR, self.binary_name), 'wb').write(server_jar.content)

    def delete(self, using=None, keep_parents=False):
        url = self.download_path
        super().delete()

        name = url.rsplit('/', 1)[-1]
        server_jar = os.path.join(settings.BINARY_DIR, name)
        if os.path.exists(server_jar):
            os.remove(server_jar)


# Create your models here.
class ServerProperties(models.Model):
    class Meta:
        verbose_name = "Server Properties"
        verbose_name_plural = "Servers Properties"

    level_name = models.CharField(max_length=500, blank=False, null=False)
    server_port = models.IntegerField(null=False, blank=False, default=25565)
    query_port = models.IntegerField(null=False, blank=False, default=25580)
    rcon_port = models.IntegerField(null=False, blank=False, default=25570)
    rcon_password = models.CharField(max_length=200, null=False, blank=False)
    server_ip = models.GenericIPAddressField(null=True, blank=True)
    enable_jmx_monitoring = models.BooleanField(default=False)
    enable_command_block = models.BooleanField(default=False)
    gamemode = models.CharField(max_length=10, choices=GAMEMODES, default='survival')
    enable_query = models.BooleanField(default=True)
    motd = models.CharField(max_length=500, blank=False, null=False, default="A Minecraft Server")
    pvp = models.BooleanField(default=True)
    difficulty = models.CharField(max_length=8, choices=DIFFICULTY, default="easy")
    network_compression_threshold = models.IntegerField(default=256, null=False, blank=False)
    max_tick_time = models.IntegerField(default=60000, null=False, blank=False)
    require_resource_pack = models.BooleanField(default=False)
    use_native_transport = models.BooleanField(default=True)
    max_players = models.IntegerField(default=20, null=False, blank=False)
    enable_status = models.BooleanField(default=True)
    online_mode = models.BooleanField(default=True)
    allow_flight = models.BooleanField(default=False)
    broadcast_rcon_to_ops = models.BooleanField(default=True)
    view_distance = models.IntegerField(default=10, null=False, blank=False)
    resource_pack_prompt = models.CharField(max_length=500, null=True, blank=True)
    allow_nether = models.BooleanField(default=True)
    enable_rcon = models.BooleanField(default=True)
    sync_chunk_writes = models.BooleanField(default=True)
    op_permission_level = models.IntegerField(default=4, validators=[MinValueValidator(1), MaxValueValidator(4)],
                                              null=False, blank=False)
    prevent_proxy_connections = models.BooleanField(default=False)
    hide_online_players = models.BooleanField(default=False)
    resource_pack = models.CharField(max_length=500, null=True, blank=True)
    entity_broadcast_range_percentage = models.IntegerField(default=100,
                                                            validators=[MinValueValidator(10), MaxValueValidator(1000)],
                                                            null=False, blank=False)
    simulation_distance = models.IntegerField(default=10, null=False, blank=False)
    player_idle_timeout = models.IntegerField(default=0, null=False, blank=False)
    debug = models.BooleanField(default=False)
    force_gamemode = models.BooleanField(default=False)
    rate_limit = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(1000)], null=False,
                                     blank=False)
    hardcore = models.BooleanField(default=False)
    white_list = models.BooleanField(default=False)
    broadcast_console_to_ops = models.BooleanField(default=True)
    spawn_npcs = models.BooleanField(default=True)
    spawn_animals = models.BooleanField(default=True)
    function_permission_level = models.IntegerField(default=2, validators=[MinValueValidator(1), MaxValueValidator(4)],
                                                    null=False, blank=False)
    text_filtering_config = models.CharField(max_length=500, null=True, blank=True)
    spawn_monsters = models.BooleanField(default=True)
    enforce_whitelist = models.BooleanField(default=False)
    resource_pack_sha1 = models.CharField(max_length=500, null=True, blank=True)
    spawn_protection = models.IntegerField(default=16, validators=[MinValueValidator(1), MaxValueValidator(1000)],
                                           null=False, blank=False)
    max_world_size = models.IntegerField(default=29999984,
                                         validators=[MinValueValidator(1), MaxValueValidator(29999984)], null=False,
                                         blank=False)

    def __str__(self):
        return self.level_name


class Server(models.Model):
    class Meta:
        verbose_name = "Server"
        verbose_name_plural = "Servers"
        permissions = (("op", "Is OP"),
                       ("restart_server", "Can restart Server"),)

    name = models.CharField(max_length=150, null=False, blank=False)
    server_properties = models.OneToOneField(ServerProperties, on_delete=models.CASCADE)
    server_binary = models.OneToOneField(ServerBin, on_delete=models.CASCADE)
    identifier = models.CharField(max_length=10, editable=False)
    server_pid = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if self.identifier is None or self.identifier == "":
            self.identifier = self.create_identifier()
        super().save()

    def create_identifier(self):
        random_string = ''
        for _ in range(10):
            # Considering only upper and lowercase letters
            random_integer = random.randint(97, 97 + 26 - 1)
            flip_bit = random.randint(0, 1)
            # Convert to lowercase if the flip bit is on
            random_integer = random_integer - 32 if flip_bit == 1 else random_integer
            # Keep appending random characters using chr(x)
            random_string += (chr(random_integer))
        return random_string

servers/views.py
import os.path
import signal
import subprocess
import sys
import threading
import time
import yaml
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.conf import settings
from .models import ServerBin, Server
from .form import ServerForm, ServerPropertiesForm, UploadFileForm
import requests
import shutil
import zipfile
import logging

logger = logging.getLogger('django')


@login_required
def index(request):
    servers = Server.objects.all()
    return render(request, 'servers/index.html', {'servers': servers})


@login_required
def binaries_overview(request):
    binaries = ServerBin.objects.all()
    return render(request, 'servers/binaries-overview.html', {'binaries': binaries})


@login_required
def new_server(request):
    stu = ServerForm()
    return render(request, "servers/new-server.html", {'form': stu})


@login_required
def edit_server(request, server_identifier):
    server = Server.objects.get(identifier=server_identifier)
    server_form = ServerForm(instance=server)
    server_properties_form = ServerPropertiesForm(instance=server.server_properties)
    upload_world_form = UploadFileForm()
    bungee_config = None

    if server.server_binary.type == 0:
        confpath = os.path.join(settings.SERVERS_DIR, server_identifier, 'config.yml')
        with open(confpath) as file:
            try:
                bungee_config = yaml.safe_load(file)
            except yaml.YAMLError as exc:
                logger.error(exc)

    return render(request, "servers/edit.html",
                  {'server_form': server_form,
                   'server_properties_form': server_properties_form,
                   'upload_world_form': upload_world_form,
                   'server': server,
                   'bungee_config': bungee_config}
                  )


@login_required
def delete_server(request, server_identifier):
    server = Server.objects.get(identifier=server_identifier)
    stop_single_server(server_identifier)
    path = os.path.join(settings.SERVERS_DIR, server_identifier)
    try:
        shutil.rmtree(path)
        messages.info(request, 'Server %s deleted' % server_identifier)
        server.delete()
    except Exception as e:
        messages.error(request, 'Error deleting server %s: %s' % (server_identifier, e))
        logger.error("Error deleting server")

    return redirect('server-overview')


@login_required
def upload_world(request, server_identifier):
    server = Server.objects.get(identifier=server_identifier)

    if server.server_pid is not None:
        stop_single_server(server_identifier)
        time.sleep(10)

    path = os.path.join(settings.SERVERS_DIR, server_identifier, 'world')

    if request.method == 'POST':
        f = request.FILES['world_file']

        dest = os.path.join(settings.TMP_DIR, f.name)
        with open(dest, 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
        try:
            shutil.rmtree(path)
        except Exception as e:
            logger.error(e)

        try:
            with zipfile.ZipFile(dest, 'r') as zip_ref:
                zip_ref.extractall(os.path.join(settings.SERVERS_DIR, server_identifier))

            with zipfile.ZipFile(dest, 'r') as f:
                names = [info.filename for info in f.infolist() if info.is_dir()]
            world_name = names[0].replace("/", "")
            server_path = os.path.join(settings.SERVERS_DIR, server_identifier)
            os.rename(os.path.join(server_path, world_name), os.path.join(server_path, 'world'))
            os.remove(dest)
        except Exception as e:
            logger.error(e)

        messages.info(request, 'Added new World, you can now start the server again')
    else:
        messages.info(request, 'That didn\'t work')
    return redirect('server-edit', server_identifier)


@login_required
def remove_world(request, server_identifier):
    path = os.path.join(settings.SERVERS_DIR, server_identifier, 'world')

    stop_single_server(server_identifier)

    try:
        shutil.rmtree(path)
        messages.info(request, 'World %s removed' % server_identifier)
    except Exception as e:
        messages.error(request, 'Error removing world %s: %s' % (server_identifier, e))

    return redirect('server-edit', server_identifier)


@login_required
def show_server_console(request, server_identifier):
    return render(request, 'servers/console.html', {'server_identifier': server_identifier})


@login_required
def start_server(request, server_identifier=None):
    if server_identifier is not None:
        if server_identifier == 'all':
            start_all_server()
            messages.info(request, 'Started all servers')
        else:
            start_single_server(server_identifier)
            messages.info(request, 'Server %s started' % server_identifier)

    return redirect('server-overview')


def start_single_server(server_identifier):
    server = Server.objects.get(identifier=server_identifier)
    if check_binary(server.server_binary):
        if not check_server_dir(server):
            create_server_dir_and_copy_binary(server)
        else:
            start_server_in_thread(server)


def start_all_server():
    logger.info("in all servers")
    servers = Server.objects.all()
    for server in servers:
        start_single_server(server.identifier)


def stop_single_server(server_identifier):
    server = Server.objects.get(identifier=server_identifier)
    try:
        os.kill(int(server.server_pid), signal.SIGTERM)
    except Exception as e:
        logger.error(e)
    server.server_pid = None
    server.save()


@login_required
def stop_server(request, server_identifier):
    if server_identifier is not None:
        if server_identifier == 'all':
            servers = Server.objects.all()
            for server in servers:
                stop_single_server(server.identifier)
        else:
            stop_single_server(server_identifier)

    messages.info(request, 'Stopped Server')

    return redirect('server-overview')


@login_required
def restart_server(request, server_identifier):
    if server_identifier is not None:
        if server_identifier == 'all':
            servers = Server.objects.all()
            for server in servers:
                stop_single_server(server.identifier)
                time.sleep(10)
                start_single_server(server.identifier)
        else:
            stop_single_server(server_identifier)
            time.sleep(10)
            start_single_server(server_identifier)

    messages.info(request, 'Restarted Server')
    return redirect('server-overview')


def start_server_in_thread(server):
    x = threading.Thread(target=start_server_thread, args=[server])
    x.start()


def start_server_thread(server):
    servercwd = os.path.join(settings.SERVERS_DIR, server.identifier)
    jarpath = os.path.join(servercwd, server.server_binary.binary_name)

    if server.server_binary.type == 3:
        gui = 'nogui'
    else:
        gui = '--nogui'

    # proc = subprocess.Popen(['python', script], shell=True, #stdout=subprocess.PIPE))

    serverprocess = subprocess.Popen(['java', '-jar', jarpath, gui], cwd=servercwd)
    server.server_pid = serverprocess.pid
    server.save()


def copy_server_binary_to_server_dir(server):
    source = os.path.join(settings.BINARY_DIR, server.server_binary.binary_name)
    destination = os.path.join(settings.SERVERS_DIR, server.identifier)
    shutil.copy(source, destination)


def create_server_dir_and_copy_binary(server):
    path = os.path.join(settings.SERVERS_DIR, server.identifier)
    os.mkdir(path)
    copy_server_binary_to_server_dir(server)
    eula_file = open(os.path.join(settings.SERVERS_DIR, server.identifier, 'eula.txt'), 'a')
    eula_file.write('eula=true')
    eula_file.close()


def check_server_dir(server):
    return os.path.exists(os.path.join(settings.SERVERS_DIR, server.identifier))


def check_binary(binary):
    return os.path.exists(os.path.join(settings.BINARY_DIR, binary.binary_name))


def download_binary(request):
    url = "https://papermc.io/api/v2/projects/paper/versions/1.18.1/builds/103/downloads/paper-1.18.1-103.jar"
    name = url.rsplit('/', 1)[-1]
    server_jar = requests.get(url)
    open(os.path.join(settings.BINARY_DIR, name), 'wb').write(server_jar.content)

    return redirect('server-overview')

templates/servers/binaries-overview.html
{% extends 'base.html' %}
{% block title %}
    MCS - Servers
{% endblock title %}
{% block content %}
    {% load static %}
    <div class="mb-3">
        <h1 class="h3 d-inline align-middle">Server Binaries</h1>
    </div>

    <div class="row mb-3">
        <div class="col-2">
            <a href="#" class="btn btn-outline-info"><i class="bi bi-plus-square"></i> Add Binary</a>
        </div>
    </div>

    <div class="row">


        {% for binary in binaries %}
            <div class="col-sm-3">
                <div class="card">
                    {% if binary.type == 0 %}
                        <img src="{% static 'img/server/bungeecord.png' %}" class="card-img-top"
                             alt="{{ binary.type.get_type_display }}">
                    {% elif binary.type == 1 %}
                        <img src="{% static 'img/server/spigot.png' %}" class="card-img-top"
                             alt="{{ binary.type.get_type_display }}">
                    {% elif binary.type == 2 %}
                        <img src="{% static 'img/server/bukkit.png' %}" class="card-img-top"
                             alt="{{ binary.type.get_type_display }}">
                    {% elif binary.type == 3 %}
                        <img src="{% static 'img/server/papermc.png' %}" class="card-img-top"
                             alt="{{ binary.type.get_type_display }}">
                    {% elif binary.type == 4 %}
                        <img src="{% static 'img/server/vanilla.png' %}" class="card-img-top"
                             alt="{{ server.server_binary.get_type_display }}">
                    {% endif %}

                    <div class="card-body">
                        <h5 class="card-title">{{ binary.name }}</h5>
                        <p class="card-text">{{ binary.get_type_display }} Version: {{ binary.version }}</p>
                        <a href="#" class="btn btn-outline-secondary"><i class="bi bi-pencil-square"></i></a>
                        <a href="#" class="btn btn-outline-danger"><i class="bi bi-trash"></i></a>
                    </div>
                </div>
            </div>

        {% endfor %}

    </div>


{% endblock %}

templates/servers/console.html
{% extends 'base.html' %}

{% block title %}
    MCS - Server Console
{% endblock title %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container">

        <textarea id="chat-log" cols="100" rows="20"></textarea><br>
        <input id="chat-message-input" type="text" size="100"><br>
        <input id="chat-message-submit" type="button" value="Send">
        {{ server_identifier|json_script:"room-name" }}
        <script>
            const roomName = JSON.parse(document.getElementById('room-name').textContent);

            const chatSocket = new WebSocket(
                'ws://'
                + window.location.host
                + '/ws/console/'
                + roomName
                + '/'
            );

            chatSocket.onmessage = function (e) {
                const data = JSON.parse(e.data);
                document.querySelector('#chat-log').value += (data.message + '\n');
            };

            chatSocket.onclose = function (e) {
                console.error('Chat socket closed unexpectedly');
            };

            document.querySelector('#chat-message-input').focus();
            document.querySelector('#chat-message-input').onkeyup = function (e) {
                if (e.keyCode === 13) {  // enter, return
                    document.querySelector('#chat-message-submit').click();
                }
            };

            document.querySelector('#chat-message-submit').onclick = function (e) {
                const messageInputDom = document.querySelector('#chat-message-input');
                const message = messageInputDom.value;
                chatSocket.send(JSON.stringify({
                    'message': message
                }));
                messageInputDom.value = '';
            };
        </script>

    </div>

{% endblock %}

templates/servers/edit.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
    MCS - New Server
{% endblock title %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container">

        <div class="mb-3">
            <h1 class="h3 d-inline align-middle">{{ server.name }}</h1>
            <small>{{ server.identifier }}</small>
        </div>

        <div class="row mb-3">
            <div class="col-sm-2">
                <a href="{% url 'server-overview' %}" class="btn btn-outline-info"><i class="bi bi-arrow-left"></i> Back</a>
            </div>
            <div class="col-sm-1">
                <a href="{% url 'server-delete' server.identifier %}" class="btn btn-outline-danger" id="delete">
                    <i class="bi bi-trash"></i>
                </a>
            </div>

            <div class="col-sm-1">
                <a href="{% url 'server-remove-world' server.identifier %}" class="btn btn-outline-danger" id="delete">
                    remove world
                </a>
            </div>
        </div>

        {% if messages %}
            {% for message in messages %}
                <div class="row">
                    <div class="col">
                        <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}


        <div class="row mb-3">
            <div class="col">
                <form method="POST" class="post-form">
                    {% csrf_token %}
                    {{ server_form | crispy }}
                    <p class="mt-3">
                        <a class="btn btn-outline-secondary" data-bs-toggle="collapse" href="#collapseExample"
                           role="button"
                           aria-expanded="false" aria-controls="collapseExample">
                            Server Properties <i class="bi bi-chevron-down"></i>
                        </a>
                    </p>
                    <div class="collapse" id="collapseExample">
                        <div class="card card-body">
                            {{ server_properties_form | crispy }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Save</button>

                </form>
            </div>
        </div>


        <div class="row">
            <form method="post" action="{% url 'server-upload-world' server.identifier %}"
                  enctype="multipart/form-data">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Upload World <small>as .zip</small></h5>
                        <p>
                            {% csrf_token %}
                            {{ upload_world_form | crispy }}
                        </p>
                        <button type="submit" class="btn btn-outline-primary">upload</button>
                    </div>
                </div>
            </form>
        </div>



    {% if bungee_config %}
        <div class="row">
            <div class="mb-3">
                <h1 class="h3 d-inline align-middle">BungeeConfig</h1>
            </div>
            <pre><code class="language-yml">{{ bungee_config }}</code></pre>
        </div>
    {% endif %}

    </div>


    <script>

        const deleteLink = document.getElementById('delete');
        deleteLink.addEventListener('click', e => confirmDelete(e));
        const confirmDelete = e => {
            const result = window.confirm('Are you sure to delete the Server?');
            if (!result) {
                e.preventDefault();
            }
        }
    </script>


{% endblock %}

templates/servers/index.html
{% extends 'base.html' %}
{% block title %}
    MCS - Servers
{% endblock title %}
{% block content %}
    {% load static %}
    <div class="mb-3">
        <h1 class="h3 d-inline align-middle">Servers</h1>
    </div>
    <div class="row mb-3">
        <div class="col">
            <a href="#" class="btn btn-outline-info">
                <i class="bi bi-plus-square"></i> Add Server </a>
            <div class="btn-group" role="group" aria-label="Basic example">
                <a href="{% url 'server-stop-server' 'all' %}" class="btn btn-outline-danger">
                    <i class="bi bi-stop"></i> Stop All Servers
                </a>
                <a href="{% url 'server-restart-server' 'all' %}" class="btn btn-outline-danger">
                    <i class="bi bi-arrow-clockwise"></i> Restart All Servers
                </a>
                <a href="{% url 'server-start-server' 'all' %}" class="btn btn-outline-secondary">
                    <i class="bi bi-play"></i> Start All Servers
                </a>
            </div>
        </div>
    </div>
    {% if messages %}
        {% for message in messages %}
            <div class="row">
                <div class="col">
                    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}

    <div class="row">
        {% if servers %}
            {% for server in servers %}
                <div class="col-sm-3">
                    <a href="{% url 'server-edit' server.identifier %}" class="card-link">
                        <div class="card">
                            {% if server.server_binary.type == 0 %}
                                <img src="{% static 'img/server/bungeecord.png' %}" class="card-img-top"
                                     alt="{{ server.server_binary.get_type_display }}">
                            {% elif server.server_binary.type == 1 %}
                                <img src="{% static 'img/server/spigot.png' %}" class="card-img-top"
                                     alt="{{ server.server_binary.get_type_display }}">
                            {% elif server.server_binary.type == 2 %}
                                <img src="{% static 'img/server/bukkit.png' %}" class="card-img-top"
                                     alt="{{ server.server_binary.get_type_display }}">
                            {% elif server.server_binary.type == 3 %}
                                <img src="{% static 'img/server/papermc.png' %}" class="card-img-top"
                                     alt="{{ server.server_binary.get_type_display }}">
                            {% elif server.server_binary.type == 4 %}
                                <img src="{% static 'img/server/vanilla.png' %}" class="card-img-top"
                                     alt="{{ server.server_binary.get_type_display }}">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ server.name }}</h5>
                                <p class="card-text mb-3">{{ server.server_binary.get_type_display }}
                                    Version: {{ server.server_binary.version }}</p>
                                <div class="btn-group" role="group" aria-label="Basic example">
                                    {% if server.server_pid is None %}
                                        <a href="{% url 'server-start-server' server.identifier %}"
                                           class="btn btn-outline-secondary"> <i class="bi bi-play"></i> Start</a>
                                    {% else %}
                                        <a href="{% url 'server-stop-server' server.identifier %}"
                                           class="btn btn-outline-danger"> <i class="bi bi-stop"></i> Stop</a>
                                        <a href="{% url 'server-restart-server' server.identifier %}"
                                           class="btn btn-outline-danger"> <i class="bi bi-arrow-clockwise"></i> Restart</a>
                                        <a href="{% url 'server-console' server.identifier %}"
                                           class="btn btn-outline-dark"><i class="bi bi-code-square"></i>
                                            Console</a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        {% else %}
            Add a server
        {% endif %}
    </div>
{% endblock %}

templates/servers/new-server.html
{% extends 'base.html' %}

{% block title %}
    MCS - New Server
{% endblock title %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <form method="POST" class="post-form">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>

{% endblock %}